repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
        exclude: ^(lib/logging/)|(staticfiles/admin/)
    -   id: end-of-file-fixer
        exclude: ^(lib/logging/)|(staticfiles/admin/)
    -   id: check-yaml
        exclude: ^(lib/logging/)|(staticfiles/admin/)
    -   id: check-added-large-files
        exclude: ^(lib/logging/)|(staticfiles/admin/)

-   repo: https://github.com/pycqa/isort
    rev: 5.6.4
    hooks:
    -   id: isort
        exclude: ^(lib/logging/)|(staticfiles/admin/)

-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
        language_version: python3
        exclude: ^(lib/logging/)|(staticfiles/admin/)

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
        args: ['--config=.flake8']
        exclude: ^(lib/logging/)|(staticfiles/admin/)
