version: '3.8'

services:
  web:
    build: ./app
    image: algocourse_web
    command: gunicorn algocourse.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      - ./app/:/usr/src/app/
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  db:
    image: postgres:12.0-alpine
    volumes:
      - ./db/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=algocourse
      - POSTGRES_PASSWORD=algocourse
      - POSTGRES_DB=algocourse_main
  adminer:
    image: adminer:4.7.7
    ports:
      - 8080:8080
    depends_on:
      - db
  nginx:
    build: ./nginx
    image: algocourse_nginx
    volumes:
      - ./app/staticfiles/:/home/app/web/staticfiles/
      - ./app/mediafiles/:/home/app/web/mediafiles/
    ports:
      - 1337:80
    depends_on:
      - web
  redis:
    image: redis:6.0.9-alpine
    ports:
      - 6380:6379
