version: '3.8'

services:
  web:
    build: ./
    image: algocourse_web
    command: gunicorn algocourse.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      # set volume to be the "app" directory and set reload flag in gunicorn
      # to make the changes to be applied automatically in the web container
      - ./:/usr/src/app/
    expose:
      # run gunicorn at port 8000 of the container and expose this port
      # so that nginx can see and set upstream at web:8000
      - 8000
    env_file:
      - ./config/.env.dev
    depends_on:
      # wait for db and redis to finish their initialization
      - db
      - redis
  db:
    image: postgres:12.0-alpine
    volumes:
      # use a real directory to store db data to maintain it even when the containers are shut down
      - ./db/:/var/lib/postgresql/data/
    environment:
      # TODO: find a way to secure the password here
      - POSTGRES_USER=algocourse
      - POSTGRES_PASSWORD=algocourse
      - POSTGRES_DB=algocourse_main
  adminer:
    image: adminer:4.7.7
    ports:
      - 9090:8080
    depends_on:
      - db
  nginx:
    build: ./nginx
    image: algocourse_nginx
    volumes:
      - ./staticfiles/:/home/app/web/staticfiles/
      - ./mediafiles/:/home/app/web/mediafiles/
    ports:
      # start nginx at port 80 in its container and connect it with port 1337 of the real device
      - 1337:80
    depends_on:
      - web
  redis:
    image: redis:6.0.9-alpine
    ports:
      # my laptop port 6379 was occupied by the real Redis, so I used 6380 instead
      - 6380:6379
