name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - name: Checkout my code
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f ./app/requirements.txt ]; then pip install -r ./app/requirements.txt; fi
      - name: Lint with flake8
        run: |
          flake8 . --count --config=.flake8 --show-source --statistics
      - name: Test with pytest
        run: |
          pytest
  push-to-docker-hub:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # https://github.com/marketplace/actions/docker-login
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        working-directory: ./app
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: farmerboy/algocourse_test:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
